### ISSUE TITLE
小白想请教问题

### ISSUE THREAD

**Issue by Qs-cic** [StarCompute/RegionData#1]
大佬，您的介绍中主要结构中字段名称有提到非国标，这里的非国标是指 “字段的命名？”还是其他的，哪里可以查看国标对地址信息字段的规范呢？另外有没有官方的渠道可以系统获取这些规范的地址信息呢？烦请大佬给予帮助~

**Comment by StarCompute** [comment]
> 
> 
> 大佬，您的介绍中主要结构中字段名称有提到非国标，这里的非国标是指 “字段的命名？”还是其他的，哪里可以查看国标对地址信息字段的规范呢？另外有没有官方的渠道可以系统获取这些规范的地址信息呢？烦请大佬给予帮助~

1，例如fullname 这种字段 是我自己为了业务的需要加上去的，里面的内容是我组合出来的，所以成为非国标。 严格意义上来说我定义的国标其实也不是国标，这里的国标指国家统计局官方数据.

2，统计局的数据地址我已经放在了介绍中，你打开查看就知道了。如果你想要数据库方式的数据官方是没有的；

**Comment by StarCompute** [comment]
> 
> 
> 大佬，您的介绍中主要结构中字段名称有提到非国标，这里的非国标是指 “字段的命名？”还是其他的，哪里可以查看国标对地址信息字段的规范呢？另外有没有官方的渠道可以系统获取这些规范的地址信息呢？烦请大佬给予帮助~

你想要的唯一的标准数据是不存在的 ，一声叹息
因为，民政部，统计局，标准委各自为政，而且涉及到行政区域的变革，所以只能选择一份相对准确的数据。也就是统计局的数据，如果不涉及第五级行政区域，目前统计局的这份数据是非常OK的了。建议使用，这是我综合考虑过后的结论。
